### ISSUE TITLE
acts_as_list doesn't play nicely with acts_as_tree

### ISSUE THREAD

**Issue by janv** [sebastiandeutsch/vrame#1]
If you move a category one level higher, double entries in the "position" column can occur.
Need to reset/recalculate positions when changing the location in the tree.

**Comment by seidtgeist** [comment]
we need
1) a working acts_as_list implementation
2) a custom implementation
to fix the whole ordering issue

**Comment by janv** [comment]
This is temporariliy fixed. We have a a better version of acts_as_list now, but I'd like to replace this whole pile of garbage with awesome_nested_set
