### ISSUE TITLE
Crashing when loading deprecated cookies

### ISSUE THREAD

**Issue by tillcarlos** [sebastiandeutsch/vrame#7]
class Vrame::CategoriesController < Vrame::VrameController line 11 reads the cookies and gives an error if it reads a category that's not present any more.

**Comment by seidtgeist** [comment]
I'll look into it. Thanks :-)

**Comment by sebastiandeutsch** [comment]
Grouped cucumber feature. Closed by e2fdc909792e4bdfb7f6e400cf417971ff91bcb4
