### ISSUE TITLE
dependency on mysql in category.rb

### ISSUE THREAD

**Issue by tillcarlos** [sebastiandeutsch/vrame#8]
named scope published was

named_scope :published, :conditions => '`categories`.`published` = 1'

i changed it to:

named_scope :published, :conditions => ['`categories`.`published` = ?', true]

works better with sqlite3!

**Comment by sebastiandeutsch** [comment]
Removed some mysql dependencies. Closed by c2ff35db16def3025f340a195fe0912eab0fbf08
